# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 08:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import localflavor.generic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='FV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('fv_date', models.DateField(default=datetime.date.today)),
                ('complete_date', models.DateField(default=datetime.date.today)),
                ('payment_method', models.CharField(choices=[('got', 'got\xf3wka'), ('prz', 'przelew'), ('rat', 'raty')], default='prz', max_length=3)),
                ('iban', localflavor.generic.models.IBANField(include_countries=None, max_length=34, use_nordea_extensions=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.ManyToManyField(to='fakturownia.Category')),
            ],
        ),
        migrations.AddField(
            model_name='fv',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakturownia.Product'),
        ),
    ]
