# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakturownia', '0003_auto_20180214_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='fv',
            name='nip',
            field=models.IntegerField(default=0, max_length=11),
        ),
    ]
