# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakturownia', '0006_auto_20180214_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fv',
            name='products',
            field=models.ManyToManyField(blank=True, to='fakturownia.Product'),
        ),
    ]
