# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakturownia', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nip',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=9),
        ),
    ]
